const zh = {
  devices: '计算设备', performance: '性能与显存', automatic: '由引擎决定', cpu: 'CPU', bundled: '随包环境',
  autoEnvironment: '自动（优先复用已有环境）', restart: '检查并应用环境', prepareRecommended: '检查计算环境', hardware: '检测到的系统显卡',
  environmentStorage: '运行环境保存位置', environmentStorageHint: '跟随模型存储位置，可在存储与下载设置中修改。',
  refresh: '刷新设备', detected: '可用计算设备', recognition: '语音识别设备', translation: '本地翻译设备',
  assignmentHint: '按模型支持和可用显存自动分配，也可分别指定；两项任务允许共用显卡。',
  nextSession: '设备与性能设置在下次启动同传时生效。', fallback: 'GPU 失败时回退 CPU',
  fallbackHint: '只对设备失效或显存不足回退，并显示实际设备；不自动更换其他指定显卡。',
  free: '可用显存', total: '总显存', unavailable: '当前模型后端不可用', network: '网络翻译不占用本地计算设备。',
  actual: '当前运行分配', recognitionActual: '识别实际设备', translationActual: '翻译实际设备',
  noSession: '尚未启动同传', shared: '共享内存设备，不能按独立显存计算容量', weakId: '设备序号可能随环境变化；启动时会重新核对',
  environments: '推理环境', engineEnvironment: 'PyTorch 环境', llamaEnvironment: 'llama.cpp 环境',
  install: '下载安装', installed: '已安装',
  localEnvironment: '本地已有环境', localPython: '已有 Python', localTorch: '已有 PyTorch', localLlama: '已有 llama.cpp', project: '项目环境',
  available: '可直接使用', notReady: '检查未通过', found: '已找到', notFound: '未找到', checkingDevices: '正在检测计算设备', deviceCheckFailed: '计算设备检测未完成，请点击刷新设备重试。',
  import: '导入离线包', cancel: '取消安装', restore: '恢复默认', repair: '重新准备并修复',
  noPackages: '当前发布版本尚未提供额外运行包；可继续使用随包环境。',
  planUnknown: '实际设备尚未确认', unloaded: '未加载',
  precision: '计算精度', precisionHint: 'PyTorch 模型按设备能力选择计算精度；CPU 默认使用 FP32。具体支持的精度由模型加载器决定。',
  quantization: '模型量化', quantHint: '仅对支持运行时量化的模型生效；NF4 / 8bit 需要兼容设备。GGUF 量化由模型文件决定，不能在此切换。不会改写模型文件。',
  none: '不量化', reserve: '保留显存（MiB）', reserveHint: '为桌面、其他应用和计算峰值留余量；两项任务共卡时一起计算预算。',
  threads: 'CPU 线程上限', threadsHint: '0 表示自动；识别与 llama 翻译共同分配线程预算。',
  layers: '翻译 GPU 卸载层数', layersHint: '-1 表示自动，0 表示 CPU；只适用于 llama.cpp 翻译。',
  context: '翻译上下文长度', contextHint: '增大会增加 KV 缓存显存需求；只适用于本地 llama.cpp。',
  flash: 'llama Flash Attention', flashHint: '自动由当前 llama 后端判断；强制开启需后端与模型支持。',
  on: '开启', off: '关闭', download: '下载中', verify: '校验中', extract: '解压中', prepare: '准备依赖中', check: '检查安装结果',
  checkingEnvironment: '准备计算环境', environmentFailed: '计算环境准备未完成', retry: '重试准备',
  useCpu: '使用 CPU 继续',
  saveError: '无法保存设置',
}
const en: typeof zh = {
  devices: 'Compute devices', performance: 'Performance & memory', automatic: 'Let the engine decide', cpu: 'CPU', bundled: 'Bundled runtime',
  autoEnvironment: 'Automatic (reuse existing runtimes first)', restart: 'Check & apply', prepareRecommended: 'Check compute environment', hardware: 'Detected system GPUs',
  environmentStorage: 'Runtime storage', environmentStorageHint: 'Follows model storage. Change it in storage settings.',
  refresh: 'Refresh devices', detected: 'Available compute devices', recognition: 'Recognition device', translation: 'Local translation device',
  assignmentHint: 'Assign by model support and available memory, or select each device. Both tasks may share a GPU.',
  nextSession: 'Device and performance changes apply to the next session.', fallback: 'Fall back to CPU on GPU failure',
  fallbackHint: 'Only device or memory failures trigger fallback. The actual device is reported; another pinned GPU is never selected silently.',
  free: 'Free VRAM', total: 'Total VRAM', unavailable: 'Unavailable for this model backend', network: 'Network translation does not use a local compute device.',
  actual: 'Current assignment', recognitionActual: 'Recognition actual device', translationActual: 'Translation actual device',
  noSession: 'No session started', shared: 'Shared memory is not counted as dedicated VRAM', weakId: 'The device index may change; it is checked again at session start',
  environments: 'Inference runtimes', engineEnvironment: 'PyTorch runtime', llamaEnvironment: 'llama.cpp runtime',
  install: 'Download & install', installed: 'Installed',
  localEnvironment: 'Existing local runtime', localPython: 'Existing Python', localTorch: 'Existing PyTorch', localLlama: 'Existing llama.cpp', project: 'Project environment',
  available: 'Ready to use', notReady: 'Check failed', found: 'Found', notFound: 'Not found', checkingDevices: 'Checking compute devices', deviceCheckFailed: 'Could not read compute devices. Click Refresh devices to retry.',
  import: 'Import offline package', cancel: 'Cancel installation', restore: 'Restore defaults', repair: 'Rebuild & repair',
  noPackages: 'This release has no additional runtime packages yet. The bundled runtime remains available.',
  planUnknown: 'Actual device not confirmed', unloaded: 'Not loaded',
  precision: 'Compute precision', precisionHint: 'Qwen / M2M100 use device capabilities; CPU uses FP32. SenseVoice keeps its model precision policy.',
  quantization: 'Model quantization', quantHint: 'Automatic uses quantization on compatible NVIDIA devices; CPU uses unquantized weights. Model files are not modified.',
  none: 'Unquantized', reserve: 'Reserved VRAM (MiB)', reserveHint: 'Leave room for the desktop, other apps and compute peaks. Both tasks share a memory budget on the same GPU.',
  threads: 'CPU thread limit', threadsHint: '0 means automatic; recognition and llama translation share the CPU budget.',
  layers: 'Translation GPU layers', layersHint: '-1 means automatic, 0 means CPU. Applies to llama.cpp translation.',
  context: 'Translation context length', contextHint: 'Larger contexts use more KV cache memory. Applies to local llama.cpp.',
  flash: 'llama Flash Attention', flashHint: 'Automatic lets the backend decide. Forced activation requires backend and model support.',
  on: 'On', off: 'Off', download: 'Downloading', verify: 'Verifying', extract: 'Extracting', prepare: 'Preparing dependencies', check: 'Checking installation',
  checkingEnvironment: 'Prepare compute environment', environmentFailed: 'Environment preparation failed', retry: 'Retry preparation', saveError: 'Could not save settings',
  useCpu: 'Continue with CPU',
}
export const computeUi = { zh, en }
