name: Upload application downloads
description: Upload two x64 installers and source ZIP as three separate files
inputs:
  exe-x64:
    required: true
    description: exe-x64 file path
  msi-x64:
    required: true
    description: msi-x64 file path
  source:
    required: true
    description: source file path
  retention-days:
    default: '14'
    description: Artifact retention period
runs:
  using: composite
  steps:
    - name: Upload exe-x64
      uses: actions/upload-artifact@v7
      with:
        path: ${{ inputs.exe-x64 }}
        archive: false
        if-no-files-found: error
        retention-days: ${{ inputs.retention-days }}
    - name: Upload msi-x64
      uses: actions/upload-artifact@v7
      with:
        path: ${{ inputs.msi-x64 }}
        archive: false
        if-no-files-found: error
        retention-days: ${{ inputs.retention-days }}
    - name: Upload source
      uses: actions/upload-artifact@v7
      with:
        path: ${{ inputs.source }}
        archive: false
        if-no-files-found: error
        retention-days: ${{ inputs.retention-days }}
